# Generated by Django 4.2.16 on 2026-07-04 11:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                        verbose_name="قیمت مصوب (ریال)",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        db_index=True,
                        help_text="تاریخی که این قیمت از آن معتبر است",
                        verbose_name="تاریخ اعتبار",
                    ),
                ),
                (
                    "expire_date",
                    models.DateField(
                        blank=True,
                        help_text="تاریخی که این قیمت منقضی می\u200cشود (معمولاً فردا)",
                        null=True,
                        verbose_name="تاریخ انقضا",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="توضیحات تکمیلی در مورد این قیمت",
                        verbose_name="توضیحات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="فعال"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_official_prices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت شده توسط",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_prices",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "union",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_prices",
                        to="organizations.union",
                        verbose_name="اتحادیه",
                    ),
                ),
            ],
            options={
                "verbose_name": "قیمت مصوب",
                "verbose_name_plural": "قیمت\u200cهای مصوب",
                "db_table": "pricing_official_price",
                "ordering": ["-effective_date", "product__name"],
            },
        ),
        migrations.CreateModel(
            name="StorePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                        verbose_name="قیمت فروشگاه (ریال)",
                    ),
                ),
                (
                    "official_price_amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="نسخه کپی قیمت مصوب برای حفظ تاریخچه",
                        max_digits=12,
                        verbose_name="قیمت مصوب در زمان ثبت (ریال)",
                    ),
                ),
                (
                    "min_allowed_price_amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="حداقل قیمت مجاز در زمان ثبت (ریال)",
                    ),
                ),
                (
                    "price_date",
                    models.DateField(
                        db_index=True,
                        help_text="تاریخی که این قیمت برای آن ثبت شده",
                        verbose_name="تاریخ قیمت",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="فعال"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_store_prices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت شده توسط",
                    ),
                ),
                (
                    "official_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_prices",
                        to="pricing.officialprice",
                        verbose_name="قیمت مصوب مرجع",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_prices",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "قیمت فروشگاه",
                "verbose_name_plural": "قیمت\u200cهای فروشگاه",
                "db_table": "pricing_store_price",
                "ordering": ["-price_date", "store__name"],
            },
        ),
        migrations.CreateModel(
            name="PriceImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="pricing/imports/%Y/%m/", verbose_name="فایل Excel"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="تاریخی که قیمت\u200cهای این فایل از آن معتبر هستند",
                        verbose_name="تاریخ اعتبار قیمت\u200cها",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پردازش"),
                            ("processing", "در حال پردازش"),
                            ("completed", "تکمیل شده"),
                            ("failed", "ناموفق"),
                            ("partial", "تکمیل ناقص"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد کل ردیف\u200cها"
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد موفق"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد خطا"),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, default=list, verbose_name="جزئیات خطاها"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پردازش"
                    ),
                ),
                (
                    "union",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_imports",
                        to="organizations.union",
                        verbose_name="اتحادیه",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آپلود شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "ورود قیمت",
                "verbose_name_plural": "ورودهای قیمت",
                "db_table": "pricing_price_import",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("official_created", "ثبت قیمت مصوب جدید"),
                            ("official_updated", "ویرایش قیمت مصوب"),
                            ("official_deactivated", "غیرفعال قیمت مصوب"),
                            ("store_created", "ثبت قیمت فروشگاه"),
                            ("store_updated", "ویرایش قیمت فروشگاه"),
                            ("store_deactivated", "غیرفعال قیمت فروشگاه"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="نوع تغییر",
                    ),
                ),
                ("union_id", models.IntegerField(verbose_name="شناسه اتحادیه")),
                (
                    "union_name",
                    models.CharField(max_length=200, verbose_name="نام اتحادیه"),
                ),
                ("product_id", models.IntegerField(verbose_name="شناسه محصول")),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="نام محصول"),
                ),
                (
                    "store_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="شناسه فروشگاه"
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام فروشگاه"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="قیمت قبلی (ریال)",
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="قیمت جدید (ریال)"
                    ),
                ),
                ("price_date", models.DateField(verbose_name="تاریخ قیمت")),
                (
                    "changed_by_name",
                    models.CharField(max_length=200, verbose_name="نام تغییردهنده"),
                ),
                (
                    "changed_by_role",
                    models.CharField(max_length=30, verbose_name="نقش تغییردهنده"),
                ),
                ("note", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تغییر داده توسط",
                    ),
                ),
                (
                    "official_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="pricing.officialprice",
                        verbose_name="قیمت مصوب",
                    ),
                ),
                (
                    "store_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="pricing.storeprice",
                        verbose_name="قیمت فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه قیمت",
                "verbose_name_plural": "تاریخچه قیمت\u200cها",
                "db_table": "pricing_price_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="storeprice",
            index=models.Index(
                fields=["store", "product", "price_date"], name="idx_store_price_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="storeprice",
            index=models.Index(
                fields=["price_date", "is_active"], name="idx_store_price_date_active"
            ),
        ),
        migrations.AddIndex(
            model_name="storeprice",
            index=models.Index(
                fields=["product", "price_date"], name="idx_store_price_product_date"
            ),
        ),
        migrations.AddIndex(
            model_name="storeprice",
            index=models.Index(
                fields=["store", "price_date"], name="idx_store_price_store_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="storeprice",
            constraint=models.UniqueConstraint(
                fields=("store", "product", "price_date"),
                name="unique_store_price_per_day",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["product_id", "price_date"], name="idx_history_product_date"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["union_id", "price_date"], name="idx_history_union_date"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["store_id", "price_date"], name="idx_history_store_date"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["change_type", "created_at"], name="idx_history_type_date"
            ),
        ),
        migrations.AddIndex(
            model_name="officialprice",
            index=models.Index(
                fields=["union", "product", "effective_date"],
                name="idx_official_price_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="officialprice",
            index=models.Index(
                fields=["effective_date", "is_active"],
                name="idx_official_price_date_active",
            ),
        ),
        migrations.AddIndex(
            model_name="officialprice",
            index=models.Index(
                fields=["product", "effective_date"], name="idx_off_price_prod_dt"
            ),
        ),
        migrations.AddConstraint(
            model_name="officialprice",
            constraint=models.UniqueConstraint(
                fields=("union", "product", "effective_date"),
                name="unique_official_price_per_day",
            ),
        ),
    ]
