# Generated by Django 4.2.16 on 2026-07-04 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تبلیغ')),
                ('image', models.ImageField(upload_to='cms/ads/%Y/%m/', verbose_name='تصویر تبلیغ')),
                ('link', models.URLField(verbose_name='لینک مقصد')),
                ('position', models.CharField(choices=[('header', 'هدر سایت'), ('sidebar', 'سایدبار'), ('footer', 'فوتر'), ('popup', 'پاپ\u200cآپ')], max_length=20, verbose_name='محل نمایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
                'db_table': 'cms_advertisement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='نامک')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی وبلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای وبلاگ',
                'db_table': 'cms_blog_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to='cms/gallery/%Y/%m/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
                'db_table': 'cms_gallery',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'db_table': 'cms_page',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='زیرنویس')),
                ('image', models.ImageField(upload_to='cms/sliders/%Y/%m/', verbose_name='تصویر اسلاید')),
                ('link', models.URLField(blank=True, verbose_name='لینک')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدرها',
                'db_table': 'cms_slider',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مطلب')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='نامک')),
                ('summary', models.TextField(verbose_name='خلاصه مطلب')),
                ('content', models.TextField(verbose_name='محتوای کامل')),
                ('image', models.ImageField(upload_to='cms/blog/%Y/%m/', verbose_name='تصویر شاخص')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='cms.blogcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مطلب وبلاگ',
                'verbose_name_plural': 'مطالب وبلاگ',
                'db_table': 'cms_blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
