# Generated by Django 4.2.16 on 2026-07-04 11:34

import apps.complaints.models.complaint
import apps.complaints.models.complaint_attachment
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="برای رهگیری عمومی شکایت توسط مشتری",
                        unique=True,
                        verbose_name="شناسه عمومی",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان شکایت")),
                ("description", models.TextField(verbose_name="شرح شکایت")),
                (
                    "price_reported",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="قیمت پرداخت\u200cشده (ریال)",
                    ),
                ),
                (
                    "price_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.complaints.models.complaint.complaint_upload_path,
                        verbose_name="مدرک قیمت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "ثبت شده"),
                            ("reviewing", "در حال بررسی"),
                            ("referred", "ارجاع داده شده"),
                            ("inspecting", "در حال بازرسی"),
                            ("confirmed", "تایید شده"),
                            ("rejected", "رد شده"),
                            ("closed", "مختومه"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True,
                        help_text="نتیجه نهایی بررسی شکایت توسط مسئول",
                        verbose_name="یادداشت نهایی (نتیجه)",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_complaints",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ارجاع داده شده به",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"role": "customer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری (شاکی)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "شکایت",
                "verbose_name_plural": "شکایات",
                "db_table": "complaints_complaint",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                ("inspection_date", models.DateField(verbose_name="تاریخ بازرسی")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("compliant", "مطابق مقررات"),
                            ("violation_found", "تخلف یافت شد"),
                            ("inconclusive", "نتیجه نامشخص"),
                        ],
                        max_length=30,
                        verbose_name="نتیجه بازرسی",
                    ),
                ),
                (
                    "notes",
                    models.TextField(verbose_name="گزارش و یادداشت\u200cهای بازرسی"),
                ),
                (
                    "complaint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection",
                        to="complaints.complaint",
                        verbose_name="شکایت مرجع",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        limit_choices_to={"role": "inspector"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بازرس",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازرسی",
                "verbose_name_plural": "بازرسی\u200cها",
                "db_table": "complaints_inspection",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("overpricing", "گران\u200cفروشی"),
                            ("underweight", "کم\u200cفروشی"),
                            ("low_quality", "کیفیت پایین"),
                            ("no_receipt", "عدم صدور فاکتور"),
                            ("other", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="نوع تخلف",
                    ),
                ),
                (
                    "fine_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="مبلغ جریمه (ریال)",
                    ),
                ),
                ("details", models.TextField(verbose_name="جزئیات تخلف")),
                (
                    "inspection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violation",
                        to="complaints.inspection",
                        verbose_name="بازرسی مرجع",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخلف",
                "verbose_name_plural": "تخلفات",
                "db_table": "complaints_violation",
            },
        ),
        migrations.CreateModel(
            name="ComplaintResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                ("response_text", models.TextField(verbose_name="متن پاسخ")),
                (
                    "is_internal_note",
                    models.BooleanField(
                        default=False,
                        help_text="اگر تیک بخورد، فقط برای مدیران قابل مشاهده است",
                        verbose_name="یادداشت داخلی",
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="complaints.complaint",
                        verbose_name="شکایت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaint_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پاسخ\u200cدهنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ شکایت",
                "verbose_name_plural": "پاسخ\u200cهای شکایات",
                "db_table": "complaints_response",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روزرسانی"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=models.FileField(
                            upload_to=apps.complaints.models.complaint_attachment.complaint_attachment_upload_path
                        ),
                        verbose_name="فایل پیوست",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="complaints.complaint",
                        verbose_name="شکایت",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaint_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آپلود شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیوست شکایت",
                "verbose_name_plural": "پیوست\u200cهای شکایات",
                "db_table": "complaints_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["status", "created_at"], name="complaints__status_39c2ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["store", "status"], name="complaints__store_i_bc64d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["customer", "created_at"], name="complaints__custome_62e905_idx"
            ),
        ),
    ]
