# Generated by Django 4.2.16 on 2026-07-31 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="کد ۸ رقمی برای نمایش به کاربر",
                max_length=8,
                null=True,
                unique=True,
                verbose_name="کد رهگیری عددی",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مشتری (شاکی)",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="resolution_note",
            field=models.TextField(blank=True, verbose_name="یادداشت نهایی (نتیجه)"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["tracking_code"], name="complaints__trackin_513965_idx"
            ),
        ),
    ]
