# Generated by Django 4.2.16 on 2026-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "complaints",
            "0002_complaint_tracking_code_alter_complaint_customer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="tracking_code",
            field=models.CharField(
                editable=False,
                help_text="کد ۸ رقمی برای نمایش به کاربر",
                max_length=8,
                unique=True,
                verbose_name="کد رهگیری عددی",
            ),
        ),
    ]
