# Generated by Django 4.2.16 on 2026-07-31 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complaints", "0003_alter_complaint_tracking_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="assigned_chamber_manager",
            field=models.ForeignKey(
                blank=True,
                help_text="اگر ۴۸ ساعت گذشت، به مدیر اتاق اصناف ارجاع می\u200cشود",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamber_assigned_complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مدیر اتاق اصناف محول شده",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="assigned_province_manager",
            field=models.ForeignKey(
                blank=True,
                help_text="اگر ۹۶ ساعت گذشت، به ناظر استانداری ارجاع می\u200cشود",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="province_assigned_complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ناظر استانداری محول شده",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="assigned_union_manager",
            field=models.ForeignKey(
                blank=True,
                help_text="شکایت اول به رئیس اتحادیه ارجاع می\u200cشود",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="union_assigned_complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="رئیس اتحادیه محول شده",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalated_at_48h",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان ارجاع ۴۸ ساعته"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalated_at_96h",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان ارجاع ۹۶ ساعته"
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="escalation_level",
            field=models.IntegerField(
                default=1,
                help_text="۱=اتحادیه، ۲=اتاق اصناف، ۳=استانداری",
                verbose_name="سطح ارجاع",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="محول شده به (فعلی)",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="tracking_code",
            field=models.CharField(
                editable=False, max_length=8, unique=True, verbose_name="کد رهگیری عددی"
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="شناسه عمومی",
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["escalation_level", "created_at"],
                name="complaints__escalat_c15653_idx",
            ),
        ),
    ]
