# Generated by Django 4.2.16 on 2026-07-04 11:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('license_number', models.CharField(help_text='شماره پروانه کسب صادر شده از اتاق اصناف', max_length=50, unique=True, verbose_name='شماره پروانه کسب')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='موبایل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='طول جغرافیایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('active', 'فعال'), ('suspended', 'تعلیق شده'), ('rejected', 'رد شده'), ('closed', 'تعطیل')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stores/images/%Y/%m/', verbose_name='تصویر فروشگاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تغییر وضعیت')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد یا تعلیق')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'store_owner'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_stores', to=settings.AUTH_USER_MODEL, verbose_name='صاحب فروشگاه')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changed_stores', to=settings.AUTH_USER_MODEL, verbose_name='تغییر وضعیت توسط')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='organizations.union', verbose_name='اتحادیه')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه\u200cها',
                'db_table': 'stores_store',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='شماره پروانه')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('expire_date', models.DateField(verbose_name='تاریخ انقضا')),
                ('issuing_authority', models.CharField(help_text='مثال: اتاق اصناف شهر تهران', max_length=200, verbose_name='مرجع صادرکننده')),
                ('business_type', models.CharField(help_text='مثال: مرغ\u200cفروشی، خواربارفروشی', max_length=200, verbose_name='نوع کسب\u200cوکار')),
                ('is_valid', models.BooleanField(db_index=True, default=True, verbose_name='معتبر')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='stores.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'پروانه کسب',
                'verbose_name_plural': 'پروانه\u200cهای کسب',
                'db_table': 'stores_license',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('document_type', models.CharField(choices=[('business_license', 'پروانه کسب'), ('national_id', 'کارت ملی'), ('store_image', 'تصویر فروشگاه'), ('health_certificate', 'گواهی بهداشت'), ('other', 'سایر')], max_length=30, verbose_name='نوع مدرک')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مدرک')),
                ('file', models.FileField(upload_to='stores/documents/%Y/%m/', verbose_name='فایل مدرک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='تایید شده')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('expire_date', models.DateField(blank=True, help_text='برای مدارکی که انقضا دارند مثل گواهی بهداشت', null=True, verbose_name='تاریخ انقضا')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stores.store', verbose_name='فروشگاه')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط')),
            ],
            options={
                'verbose_name': 'مدرک فروشگاه',
                'verbose_name_plural': 'مدارک فروشگاه',
                'db_table': 'stores_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['union', 'status'], name='idx_store_union_status'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner', 'status'], name='idx_store_owner_status'),
        ),
    ]
