# Generated by Django 4.2.16 on 2026-07-04 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('name', models.CharField(help_text='مثال: اتاق اصناف شهر تهران', max_length=200, verbose_name='نام اتاق اصناف')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('established_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال تأسیس')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='chamber', to='geography.city', verbose_name='شهر')),
                ('manager', models.OneToOneField(blank=True, limit_choices_to={'role': 'chamber_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_chamber', to=settings.AUTH_USER_MODEL, verbose_name='مدیر اتاق اصناف')),
            ],
            options={
                'verbose_name': 'اتاق اصناف',
                'verbose_name_plural': 'اتاق\u200cهای اصناف',
                'db_table': 'organizations_chamber',
                'ordering': ['city__province__name', 'city__name'],
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('name', models.CharField(help_text='مثال: اتحادیه مرغ\u200cفروشان', max_length=200, verbose_name='نام اتحادیه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره پروانه')),
                ('established_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال تأسیس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='unions/logos/%Y/%m/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unions', to='organizations.chamber', verbose_name='اتاق اصناف')),
                ('manager', models.OneToOneField(blank=True, limit_choices_to={'role': 'union_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_union', to=settings.AUTH_USER_MODEL, verbose_name='رئیس اتحادیه')),
            ],
            options={
                'verbose_name': 'اتحادیه',
                'verbose_name_plural': 'اتحادیه\u200cها',
                'db_table': 'organizations_union',
                'ordering': ['chamber__city__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('name', models.CharField(help_text='مثال: استانداری استان تهران', max_length=200, verbose_name='نام دفتر استانداری')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('manager', models.OneToOneField(blank=True, limit_choices_to={'role': 'province_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_province_office', to=settings.AUTH_USER_MODEL, verbose_name='مدیر استانداری')),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='office', to='geography.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'دفتر استانداری',
                'verbose_name_plural': 'دفاتر استانداری',
                'db_table': 'organizations_province_office',
                'ordering': ['province__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='union',
            constraint=models.UniqueConstraint(fields=('chamber', 'name'), name='unique_union_per_chamber'),
        ),
    ]
